### PR TITLE
Updated AppSource URL for the Rank Model Tuning Application.

### PR DESCRIPTION
**Pull request by MatthewMcD**
I updated the AppSource URL since it was 404. Sorry about the removal of all the white space, I think that is a VS Code "helper".

### CODE REVIEW

**Comment by wobba** [comment]
Can you remove the URL as I've removed the app from the store?

**Comment by MatthewMcD** [comment]
OK, the App is still in AppSource. I removed the "Promo".

**Comment by wobba** [comment]
Thank you. Removed it yesterday and takes 90 days for it to be inactive :)

**Comment by MatthewMcD** [comment]
BAM! Fastest PR EVER! :)

**Pull request merged**
